### ISSUE TITLE
Fix TFC class/map configs when connected to a server running an old TFC version

### ISSUE THREAD

**Issue by Joolleh** [ValveSoftware/halflife#2147]
Class configs still need to be loaded amnually - the setinfo commands aren't doing anything. Please Help ? Some players still play TFC fairly competetively in organised 4v4 matches and changing class midway through a game has become unnecessarily slow. ( you have to open the console and type exec (your class config).cfg

**Comment by SamVanheer** [comment]
#2112 still tracks this issue, you should respond to my query there so we figure out what the problem is.

**Comment by Joolleh** [comment]
o the way it has been working for years is that when you change class, if you have custom settings in your class configs, they will be executed when you change class. Now, when in an online server ( i haven't checked anything else ) both when you join the server and choose a class for the first time and when you change classes the custom settings in your class configs don't execute anymore. But if you open the console and for example type exec medic.cfg any custom settings in that file will then execute. We in the remaining orgnised player base in Australia would really appreciate it if this change can be undone and things are put back the way they have always been. i.e the class configs again execute automatically when you change class. Here is an example of the sorts of custom commands I am talking about - this is from my soldier.cfg file

echo SOLDIER CFG LOADED

fps_max 119.5

alias prime1 "primeone;spk vox/mytimer;alias grens1 throw1"
alias prime2 "primetwo;spk vox/mytimer;alias grens2 throw2"
alias throw1 "throwgren;alias grens1 prime1"
alias throw2 "throwgren;alias grens2 prime2"
alias grens1 prime1
alias grens2 prime2
bind "e" "grens1"
bind "f" "grens2"
bind SPACE "+jump"

alias mrzoom_in "fov 110; sensitivity 80; developer 1; echo Zoom in!; developer 0; alias mrzoom mrzoom_out"
alias mrzoom_out "fov 0; sensitivity 88; developer 1; echo Zoom out; developer 0; alias mrzoom mrzoom_in"
alias mrzoom mrzoom_in

alias quick1 "tf_weapon_supershotgun;mrzoom;wait;alias quickweapon quick2"
alias quick2 "tf_weapon_rpg;mrzoom;wait;alias quickweapon quick1"
alias quickweapon quick1
bind "mouse2" "quickweapon"

bind "SHIFT" "grens2"

//bind "mouse2" "+shotty"

alias "+shotty" "tf_weapon_supershotgun"
alias "-shotty" "lastinv"

bind "MWHEELUP" "dropitems;hijump"

sensitivity 88
r_drawviewmodel "0"
@Joolleh

**Comment by Joolleh** [comment]
woops didnt mean to close this.

**Comment by mikela-valve** [comment]
Since #2112 is technically fixed, I’m going to use this issue to implement the legacy support I detailed [here](https://github.com/ValveSoftware/halflife/issues/2112#issuecomment-485561130) to fix this for players running the new client on servers not running the latest update. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mikela-valve** [comment]
Will be fixed in next beta. I re-enabled `exec` as an unprivileged command specifically for TFC but changed handler to test all unprivileged configs against a whitelist, currently composed only of the TFC class/map configs.

**Comment by mikela-valve** [comment]
Fixed in 'Exe build: 11:12:36 May 21 2019 (8244)'.

**Comment by ChaosSpoofer** [comment]
The fix doesn't seem to be working for me running the beta (June 25th 8279) and joining servers running older versions (BUILD 6027).

> Server tried to send invalid command:"cl_forwardspeed 400
cl_backspeed 400
cl_sidespeed 400
"

BUILD 6027 SERVER (0 CRC)
Server # 39
Server tried to send invalid command:"exec mapdefault.cfg
exec coast_l.cfg
"
Server tried to send invalid command:"exec sniper.cfg
"
>

**Comment by ChaosSpoofer** [comment]
Also, if there's a specific whitelist, does that mean custom map cfgs won't execute?  I'm surprised "exec coast_l.cfg" in the above example didn't display an error.  Not that my test coast_l.cfg seemed to run anyway.

**Comment by ChaosSpoofer** [comment]
@mikela-valve This still isn't fixed, as I outlined above.  Can this be re-opened until it's fixed?

**Comment by mikela-valve** [comment]
Hi @ChaosSpoofer, sorry about that. Based on your console logs I tracked down what was still blocking the `exec` commands from running on legacy servers and fixed it for TFC. 

I've just updated the beta with the change (it wasn't a full build so the build number is still 8279), let me know if it still isn't working for you for some reason.

**Comment by ChaosSpoofer** [comment]
@mikela-valve  It finally works again, thanks a lot.  :D

I may as well plug two other significant issues I think many TFCers want to see fixed:

https://github.com/ValveSoftware/halflife/issues/2343 (solution offered)
https://github.com/ValveSoftware/halflife/issues/2493 (I imagine it would be simplish to switch the behavior from server to client-based)
