### ISSUE TITLE
25th Anniversary breaks mods.

### ISSUE THREAD

**Issue by CptFoxer** [ValveSoftware/halflife#3415]
Launching any Half-Life 1 after the 25th anniversary update causes an error after the intro video, preventing you from playing them.
![image](https://github.com/ValveSoftware/halflife/assets/104455743/242e5470-83a3-4ca5-9c8b-c7530dac8d8d)

**Comment by SamVanheer** [comment]
Read the anniversary post in full, it addresses mod support: https://www.half-life.com/en/halflife25/

**Comment by SamVanheer** [comment]
The wording makes it clear that mods built for older versions need to be run under the `steam_legacy` branch.

**Comment by CptFoxer** [comment]
I realized why older mods like Deliverance and Sweet Half-Life crashed, I had a custom TrackerScheme.res to increase ingame text from it's original size to it's 1080p size equivalent.

**Comment by JoelTroch** [comment]
> I realized why older mods like Deliverance and Sweet Half-Life crashed, I had a custom TrackerScheme.res to increase ingame text from it's original size to it's 1080p size equivalent. This is no longer required with the 25th Anniversary Update.

Related to https://github.com/ValveSoftware/halflife/issues/3412#issuecomment-1816962750

**Comment by OpenRift412** [comment]
> I realized why older mods like Deliverance and Sweet Half-Life crashed, I had a custom TrackerScheme.res to increase ingame text from it's original size to it's 1080p size equivalent. This is no longer required with the 25th Anniversary Update.

Hopefully this will not be the case permanently, so people don't have to keep switching back and forth.

**Comment by SamVanheer** [comment]
> how to use this steam_legacy branch?

Read this: https://twhl.info/thread/view/20055?page=4#post-348054

**Comment by SamVanheer** [comment]
It's only available on Half-Life itself, not any other GoldSource engine game. If it still doesn't show up restart Steam and see if it's there.

**Comment by SamVanheer** [comment]
You need to switch the setting on Half-Life, not Counter-Strike. CS uses the same engine files as HL.

**Comment by SamVanheer** [comment]
That should be everything. Make sure HL is up-to-date and then launch CS.

**Comment by Balimbanana** [comment]
Mods do work in Anniversary Edition, you need to change a resource file for new keyvalues that were added the exact missing lines:
In Half-Life\<modname>\resource\TrackerScheme.res inside the BaseSettings block, you need to add:

	"ProportionalBaseWidth" "1280"        // if the display resolution is above this,
	"ProportionalBaseHeight" "720"        //  ui elements will be scaled.

and the main menu will function normally. These are new settings added by the HL Anniversary update, so those settings won't be in any of the custom menus for mods.

This is specific to this posts Assert ListPanel.cpp and no menu rendering.

**Comment by FreeSlave** [comment]
> In Half-Life<modname>\resource\TrackerScheme.res inside the BaseSettings block, you need to add:

Thanks for finding this out. I wish devs set these values automatically if the `TrackerScheme.res` of the mod is missing these values. This would make current mod uploads working again.

**Comment by FreeSlave** [comment]
Seems to be fixed in the latest update? ProportionalBaseWidth and ProportionalBaseHeight are not required for mod to start correctly anymore. Please confirm.

**Comment by SamVanheer** [comment]
Mods that use the IFileSystem interface work properly again. I don't know if mods with custom resource files work since i don't have any of those installed.

**Comment by flaphoschi** [comment]
Linux is also affected. Counter-Strike 1 exists immediately without a hint.
I wonder why Valve didn't tested that especially for Counter-Strike, they even mention Counter-Strike 1 in the release website:

```
Improved client-side prediction to reduce "ghost shots". Like Counter-Strike, consider hitboxes and not just bounding boxes for hits on the client.
```

**Comment by Balimbanana** [comment]
The `Assert ListPanel.cpp` in the first post of this thread and render issue of the main menu does appear to be fixed now as of the latest update Nov 19th.

There are still some other custom mods that are having issues once getting in to the game, but most mods that I have tried will get to the main menu correctly without modifications.

**Comment by ganthore** [comment]
The Specialists 3.0 crashes on map load when running that latest anniversary update. 

Glad that steam_legacy is around until stuff like this gets fixed. 

https://www.moddb.com/mods/the-specialists

**Comment by flaphoschi** [comment]
Fixed for *Counter-Strike 1* with release from `2023-11-22`.

**Comment by marigi64** [comment]
Action Half-Life crashes not long after loading into a map

![action half-life crash](https://github.com/ValveSoftware/halflife/assets/53112738/62eb141a-784d-4f5d-99ce-ac2ea1a6cdb0)

**Comment by OpenRift412** [comment]
> Action Half-Life crashes not long after loading into a map
> 
> ![action half-life crash](https://private-user-images.githubusercontent.com/53112738/291907349-62eb141a-784d-4f5d-99ce-ac2ea1a6cdb0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODA4NDMsIm5iZiI6MTcwMzA4MDU0MywicGF0aCI6Ii81MzExMjczOC8yOTE5MDczNDktNjJlYjE0MWEtNzg0ZC00ZjVkLTk5Y2UtYWMyZWExYTZjZGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDEzNTU0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MmI1NTRhZDcwMjk5NzExMGRhMTY1MzM4NmU0OTU0ZGViMDA3NDAzMGQ2MmQzZGViYTk0MjY1ZGE4Njg0NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AkOV2t49YOCnMyY5ILKcaDB1TiFbW8h13SsgbFU1cS4)

I would recommend reinstalling it, I was actually playing AHL yesterday and it worked fine.

**Comment by marigi64** [comment]
Although it still crashes for me after reinstalling, I realised that it only crashes when in a team match (this was tested with bots so it could be related to them). The other game modes ran without problems.

**Comment by kisak-valve** [comment]
Closing because this issue appears to be resolved.

If anyone is seeing follow up issues, those issues should be tracked separately.
